# Global settings
debug: False

# Model settings
model:
  architecture: "SwinUNETR"
  pretrained: false
  feature_size: 48
  in_channels: 1
  out_channels: 1

# Training settings
training:
  epochs: 200
  batch_size: 4
  learning_rate: 1e-4

# Data settings
data:
  patch_size: [64, 64, 64]
  train_val_split: 0.8
  task1: True

# Inference settings
inference:
  sw_batch_size: 1
  overlap: 0.5
  mode: "gaussian"

# MLFlow settings
mlflow:
  tracking_uri: "file:./mlruns"  # Local storage, change to remote server if needed
  register_model: true
  log_images: true
  tags:
    project: "medical_translation"
    data_version: "v1"

