# Global settings
debug: False
# debug: True

# Training settings
training:
  epochs: 300
  batch_size: 4
  learning_rate: 1e-3
  adv_weight: 1e-2
  perceptual_weight: 1e-2
  kl_weight: 5e-4
  warmup_epochs: 5
  val_interval: 5
  save_interval: 20

# Data settings
data:
  patch_size: [64, 64, 64]
  train_val_split: 0.8
  task1: True


# Inference settings
inference:
  sw_batch_size: 2
  overlap: 0.7
  mode: "gaussian"

# MLFlow settings
mlflow:
  tracking_uri: "file:./mlruns"  # Local storage, change to remote server if needed
  register_model: true
  log_images: true
  tags:
    project: "medical_translation"
    data_version: "v1"

