# Global settings
debug: False
# debug: False

# Training settings
training:
  epochs: 500
  batch_size: 8
  learning_rate: 1e-3
  pixel_wise_weight: 0
  perceptual_weight: 1e-1
  ssim_weight: 1
  focal_frequency_weight: 1e-1
  adv_weight: 1e-2
  max_kl_weight: 1e-4
  kl_annealing_cycles: 2
  kl_annealing_ratio: 0.75
  warmup_epochs: 5
  val_interval: 20
  save_interval: 20

# Data settings
data:
  patch_size: [64, 64, 64]
  train_split: 0.70
  val_split: 0.10
  test_split: 0.20
  task1: True

# Inference settings
inference:
  sw_batch_size: 12
  overlap: 0.75
  mode: "gaussian"

# MLFlow settings
mlflow:
  tracking_uri: "file:./mlruns"  # Local storage, change to remote server if needed
  experiment_name: "COMPOUND_5"
  register_model: true
  log_original_volume: True
  log_images: true
  tags:
    project: "medical_translation"
    data_version: "v1"


